# TCL File Generated by Component Editor 16.1
# Thu Dec 15 09:57:25 GMT 2016
# DO NOT MODIFY


# 
# mdio_interface "MDIO interface" v16.1
# Ji Dong 2016.12.15.09:57:25
# MDIO interface
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mdio_interface
# 
set_module_property DESCRIPTION "MDIO interface"
set_module_property NAME mdio_interface
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Interfaces/Enet"
set_module_property AUTHOR "Ji Dong"
set_module_property DISPLAY_NAME "MDIO interface"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL mdio_interface_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file mdio_interface.vhd VHDL PATH mdio_interface.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point mdiopad
# 
add_interface mdiopad conduit end
set_interface_property mdiopad associatedClock ""
set_interface_property mdiopad associatedReset ""
set_interface_property mdiopad ENABLED true
set_interface_property mdiopad EXPORT_OF ""
set_interface_property mdiopad PORT_NAME_MAP ""
set_interface_property mdiopad CMSIS_SVD_VARIABLES ""
set_interface_property mdiopad SVD_ADDRESS_GROUP ""

add_interface_port mdiopad mdc_pad mdc Input 1
add_interface_port mdiopad mdio_in_pad mdio_in Output 1
add_interface_port mdiopad mdio_out_pad mdio_out Input 1
add_interface_port mdiopad mdio_oen_pad mdio_oen Input 1


# 
# connection point mdio
# 
add_interface mdio conduit end
set_interface_property mdio associatedClock ""
set_interface_property mdio associatedReset ""
set_interface_property mdio ENABLED true
set_interface_property mdio EXPORT_OF ""
set_interface_property mdio PORT_NAME_MAP ""
set_interface_property mdio CMSIS_SVD_VARIABLES ""
set_interface_property mdio SVD_ADDRESS_GROUP ""

add_interface_port mdio mdc mdc Output 1
add_interface_port mdio mdio mdio Bidir 1

