# TCL File Generated by Component Editor 16.1
# Wed Dec 21 11:52:59 GMT 2016
# DO NOT MODIFY


# 
# mac_filter "MAC Filter" v16.1
# Ji Dong 2016.12.21.11:52:59
# MAC Filter
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module mac_filter
# 
set_module_property DESCRIPTION "MAC Filter"
set_module_property NAME mac_filter
set_module_property VERSION 16.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Basic Functions/Interfaces/Enet"
set_module_property AUTHOR "Ji Dong"
set_module_property DISPLAY_NAME "MAC Filter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false
set_module_property ELABORATION_CALLBACK elaborate

# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL EnetMACDataFilter
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file enet_mac_filter.vhd VHDL PATH rtl/enet_mac_filter.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter enableBypass         BOOLEAN false ""

# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clock_clk clk Input 1


# 
# connection point clock_reset
# 
add_interface clock_reset reset end
set_interface_property clock_reset associatedClock clock
set_interface_property clock_reset synchronousEdges DEASSERT
set_interface_property clock_reset ENABLED true
set_interface_property clock_reset EXPORT_OF ""
set_interface_property clock_reset PORT_NAME_MAP ""
set_interface_property clock_reset CMSIS_SVD_VARIABLES ""
set_interface_property clock_reset SVD_ADDRESS_GROUP ""

add_interface_port clock_reset csi_clock_reset reset Input 1


# 
# connection point in
# 
add_interface in avalon_streaming end
set_interface_property in associatedClock clock
set_interface_property in associatedReset clock_reset
set_interface_property in dataBitsPerSymbol 8
set_interface_property in errorDescriptor ""
set_interface_property in firstSymbolInHighOrderBits true
set_interface_property in maxChannel 0
set_interface_property in readyLatency 0
set_interface_property in ENABLED true
set_interface_property in EXPORT_OF ""
set_interface_property in PORT_NAME_MAP ""
set_interface_property in CMSIS_SVD_VARIABLES ""
set_interface_property in SVD_ADDRESS_GROUP ""

add_interface_port in asi_in_ready ready Output 1
add_interface_port in asi_in_valid valid Input 1
add_interface_port in asi_in_startofpacket startofpacket Input 1
add_interface_port in asi_in_endofpacket endofpacket Input 1
add_interface_port in asi_in_empty empty Input 2
add_interface_port in asi_in_data data Input 32
add_interface_port in asi_in_error error Input 6


# 
# connection point bypass
# 
add_interface bypass avalon_streaming start
set_interface_property bypass associatedClock clock
set_interface_property bypass associatedReset clock_reset
set_interface_property bypass dataBitsPerSymbol 8
set_interface_property bypass errorDescriptor ""
set_interface_property bypass firstSymbolInHighOrderBits true
set_interface_property bypass maxChannel 0
set_interface_property bypass readyLatency 0
set_interface_property bypass ENABLED true
set_interface_property bypass EXPORT_OF ""
set_interface_property bypass PORT_NAME_MAP ""
set_interface_property bypass CMSIS_SVD_VARIABLES ""
set_interface_property bypass SVD_ADDRESS_GROUP ""

add_interface_port bypass aso_bypass_ready ready Input 1
add_interface_port bypass aso_bypass_valid valid Output 1
add_interface_port bypass aso_bypass_startofpacket startofpacket Output 1
add_interface_port bypass aso_bypass_endofpacket endofpacket Output 1
add_interface_port bypass aso_bypass_empty empty Output 2
add_interface_port bypass aso_bypass_data data Output 32
add_interface_port bypass aso_bypass_error error Output 1


# 
# connection point out
# 
add_interface out avalon_streaming start
set_interface_property out associatedClock clock
set_interface_property out associatedReset clock_reset
set_interface_property out dataBitsPerSymbol 8
set_interface_property out errorDescriptor ""
set_interface_property out firstSymbolInHighOrderBits true
set_interface_property out maxChannel 0
set_interface_property out readyLatency 0
set_interface_property out ENABLED true
set_interface_property out EXPORT_OF ""
set_interface_property out PORT_NAME_MAP ""
set_interface_property out CMSIS_SVD_VARIABLES ""
set_interface_property out SVD_ADDRESS_GROUP ""

add_interface_port out aso_out_ready ready Input 1
add_interface_port out aso_out_valid valid Output 1
add_interface_port out aso_out_startofpacket startofpacket Output 1
add_interface_port out aso_out_endofpacket endofpacket Output 1
add_interface_port out aso_out_empty empty Output 2
add_interface_port out aso_out_data data Output 32
add_interface_port out aso_out_error error Output 6


# 
# connection point cfg
# 
add_interface cfg avalon_streaming end
set_interface_property cfg associatedClock clock
set_interface_property cfg associatedReset clock_reset
set_interface_property cfg dataBitsPerSymbol 8
set_interface_property cfg errorDescriptor ""
set_interface_property cfg firstSymbolInHighOrderBits true
set_interface_property cfg maxChannel 0
set_interface_property cfg readyLatency 0
set_interface_property cfg ENABLED true
set_interface_property cfg EXPORT_OF ""
set_interface_property cfg PORT_NAME_MAP ""
set_interface_property cfg CMSIS_SVD_VARIABLES ""
set_interface_property cfg SVD_ADDRESS_GROUP ""

add_interface_port cfg asi_filter_data data Input 80


proc elaborate {} {
    set enable_bypass     [ get_parameter_value "enableBypass" ]
    
    if {$enable_bypass } {
        set_interface_property bypass ENABLED true
    } else  {
        set_interface_property bypass ENABLED false
        
    }
}
